server:
  port: 8082
resource:
  addr: http://localhost:8081/

security:
  basic:
    enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          client: DEBUG
#        boot:
#          autoconfigure: DEBUG